formatter: markdown
output-file: "README.md"
output-mode: inject

content: |
  {{ .Header }}
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Modules }}
  {{ .Resources }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Footer }}


header-from: "docs/.header.md"
footer-from: "docs/.footer.md"

sections:
  hide: []  # Do not hide any sections by default

sort:
  enabled: true
  type: name

settings:
  anchor: true
  color: true
  indent: 2
  required: true
  sensitive: true
  type: true
  default: true
