name: Generate Terraform Docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-docs:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Specify your Terraform version

      # Step 3: Run terraform-docs
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          working-dir: .
          git-push: "true"
          git-commit-message: "automation: terraform docs updated"
