name: Check Required Files and Folders

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Step 2: Check if all the required files and folders present
      - name: Verify required files and folders
        run: |
          required_items=(
            "README.md"
            "docs/"
            "docs/.header.md"
            "docs/.footer.md"
            ".config"
            ".config/.terraform-docs.yml"
            "examples"
            "tests"
            "main.tf"
            "variables.tf"
            "versions.tf"
            "outputs.tf"
            ".gitignore"
          )

          for item in "${required_items[@]}"; do
            if [ ! -e "$item" ]; then
              echo "Error: $item is missing"
              exit 1
            fi
          done
          echo "All required files and folders are present"
